//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace UiPathTeam.Excel.Extensions.Activities.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("UiPathTeam.Excel.Extensions.Activities.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        public static string Adsfadf_Description {
            get {
                return ResourceManager.GetString("Adsfadf_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Adsfadf.
        /// </summary>
        public static string Adsfadf_DisplayName {
            get {
                return ResourceManager.GetString("Adsfadf_DisplayName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Authentication.
        /// </summary>
        public static string Authentication_Category {
            get {
                return ResourceManager.GetString("Authentication_Category", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Common.
        /// </summary>
        public static string Common_Category {
            get {
                return ResourceManager.GetString("Common_Category", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to If set, continue executing the remaining activities even if the current activity has failed..
        /// </summary>
        public static string ContinueOnError_Description {
            get {
                return ResourceManager.GetString("ContinueOnError_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ContinueOnError.
        /// </summary>
        public static string ContinueOnError_DisplayName {
            get {
                return ResourceManager.GetString("ContinueOnError_DisplayName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Converts Range to HTML Code.
        /// </summary>
        public static string ConvertRangeToHTMLCode_Description {
            get {
                return ResourceManager.GetString("ConvertRangeToHTMLCode_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ConvertRangeToHTMLCode.
        /// </summary>
        public static string ConvertRangeToHTMLCode_DisplayName {
            get {
                return ResourceManager.GetString("ConvertRangeToHTMLCode_DisplayName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delete columns between the columns.
        /// </summary>
        public static string DeleteBetweenColumns_Description {
            get {
                return ResourceManager.GetString("DeleteBetweenColumns_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delete Between Columns.
        /// </summary>
        public static string DeleteBetweenColumns_DisplayName {
            get {
                return ResourceManager.GetString("DeleteBetweenColumns_DisplayName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Deletes duplicate columns.
        /// </summary>
        public static string DeleteDuplicateColumns_Description {
            get {
                return ResourceManager.GetString("DeleteDuplicateColumns_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to DeleteDuplicateColumns.
        /// </summary>
        public static string DeleteDuplicateColumns_DisplayName {
            get {
                return ResourceManager.GetString("DeleteDuplicateColumns_DisplayName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Deletes empty columns in the Range.
        /// </summary>
        public static string DeleteEmptyColumns_Description {
            get {
                return ResourceManager.GetString("DeleteEmptyColumns_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delete Empty Columns.
        /// </summary>
        public static string DeleteEmptyColumns_DisplayName {
            get {
                return ResourceManager.GetString("DeleteEmptyColumns_DisplayName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Deletes Empty Rows from the range.
        /// </summary>
        public static string DeleteEmptyRows_Description {
            get {
                return ResourceManager.GetString("DeleteEmptyRows_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delete Empty Rows.
        /// </summary>
        public static string DeleteEmptyRows_DisplayName {
            get {
                return ResourceManager.GetString("DeleteEmptyRows_DisplayName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Do.
        /// </summary>
        public static string Do {
            get {
                return ResourceManager.GetString("Do", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Excel Extensions Scope.
        /// </summary>
        public static string ExcelExtensionsScope_Description {
            get {
                return ResourceManager.GetString("ExcelExtensionsScope_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Excel Extensions Scope.
        /// </summary>
        public static string ExcelExtensionsScope_DisplayName {
            get {
                return ResourceManager.GetString("ExcelExtensionsScope_DisplayName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Excel File Path.
        /// </summary>
        public static string ExcelExtensionsScope_FilePath_Description {
            get {
                return ResourceManager.GetString("ExcelExtensionsScope_FilePath_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to FilePath.
        /// </summary>
        public static string ExcelExtensionsScope_FilePath_DisplayName {
            get {
                return ResourceManager.GetString("ExcelExtensionsScope_FilePath_DisplayName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Input.
        /// </summary>
        public static string Input_Category {
            get {
                return ResourceManager.GetString("Input_Category", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to asdfasdf.
        /// </summary>
        public static string NormalAct_Description {
            get {
                return ResourceManager.GetString("NormalAct_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to NormalAct.
        /// </summary>
        public static string NormalAct_DisplayName {
            get {
                return ResourceManager.GetString("NormalAct_DisplayName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Options.
        /// </summary>
        public static string Options_Category {
            get {
                return ResourceManager.GetString("Options_Category", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Output.
        /// </summary>
        public static string Output_Category {
            get {
                return ResourceManager.GetString("Output_Category", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Test.
        /// </summary>
        public static string Test_Description {
            get {
                return ResourceManager.GetString("Test_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Test.
        /// </summary>
        public static string Test_DisplayName {
            get {
                return ResourceManager.GetString("Test_DisplayName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to test scope.
        /// </summary>
        public static string TestScope_Description {
            get {
                return ResourceManager.GetString("TestScope_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to TestScope.
        /// </summary>
        public static string TestScope_DisplayName {
            get {
                return ResourceManager.GetString("TestScope_DisplayName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to s v 1.
        /// </summary>
        public static string TestScope_ScopeVar1_Description {
            get {
                return ResourceManager.GetString("TestScope_ScopeVar1_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ScopeVar1.
        /// </summary>
        public static string TestScope_ScopeVar1_DisplayName {
            get {
                return ResourceManager.GetString("TestScope_ScopeVar1_DisplayName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to s v 2.
        /// </summary>
        public static string TestScope_ScopeVar2_Description {
            get {
                return ResourceManager.GetString("TestScope_ScopeVar2_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ScopeVar2.
        /// </summary>
        public static string TestScope_ScopeVar2_DisplayName {
            get {
                return ResourceManager.GetString("TestScope_ScopeVar2_DisplayName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to description.
        /// </summary>
        public static string TestScopeD2_Description {
            get {
                return ResourceManager.GetString("TestScopeD2_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to TestScopeD2.
        /// </summary>
        public static string TestScopeD2_DisplayName {
            get {
                return ResourceManager.GetString("TestScopeD2_DisplayName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to sadf sfdas.
        /// </summary>
        public static string TestScopeD2_P1_Description {
            get {
                return ResourceManager.GetString("TestScopeD2_P1_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to p1.
        /// </summary>
        public static string TestScopeD2_P1_DisplayName {
            get {
                return ResourceManager.GetString("TestScopeD2_P1_DisplayName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to sdfa sdfas.
        /// </summary>
        public static string TestScopeD2_P2_Description {
            get {
                return ResourceManager.GetString("TestScopeD2_P2_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to p2.
        /// </summary>
        public static string TestScopeD2_P2_DisplayName {
            get {
                return ResourceManager.GetString("TestScopeD2_P2_DisplayName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Specifies the amount of time (in milliseconds) to wait for the activity to run before an error is thrown. The default value is 60000 (1 minute)..
        /// </summary>
        public static string Timeout_Description {
            get {
                return ResourceManager.GetString("Timeout_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Timeout (milliseconds).
        /// </summary>
        public static string Timeout_DisplayName {
            get {
                return ResourceManager.GetString("Timeout_DisplayName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The activity timed out and was canceled..
        /// </summary>
        public static string Timeout_Error {
            get {
                return ResourceManager.GetString("Timeout_Error", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please provide a value either for {0} or {1}, but not both..
        /// </summary>
        public static string ValidationExclusiveProperties_Error {
            get {
                return ResourceManager.GetString("ValidationExclusiveProperties_Error", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please provide values for both {0} and {1}..
        /// </summary>
        public static string ValidationOverloadGroup_Error {
            get {
                return ResourceManager.GetString("ValidationOverloadGroup_Error", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cannot be used outside of a {0}..
        /// </summary>
        public static string ValidationScope_Error {
            get {
                return ResourceManager.GetString("ValidationScope_Error", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please provide a value for {0}..
        /// </summary>
        public static string ValidationValue_Error {
            get {
                return ResourceManager.GetString("ValidationValue_Error", resourceCulture);
            }
        }
    }
}
